import { Component } from '@angular/core';
import jsPDF from 'jspdf';
import { FileSaverModule, FileSaverService } from 'ngx-filesaver';
import { TableModule } from 'primeng/table';
import { TooltipModule } from 'primeng/tooltip';

@Component({
  selector: 'app-table',
  standalone: true,
  imports: [TableModule, FileSaverModule, TooltipModule],
  templateUrl: './table.component.html',
  styleUrl: './table.component.css',
})
export class TableComponent {
  constructor(private fileSaverService: FileSaverService) {}

  downloadPDF() {
    const doc = new jsPDF();

    // Add content to the PDF
    doc.text('Ticket number ', 10, 10);

    // Convert PDF to Blob
    const pdfBlob = doc.output('blob');

    // Save the PDF file using ngx-filesaver
    this.fileSaverService.save(pdfBlob, 'download.pdf');
  }
  products1: any[] = [
    {
      code: '1',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '0115522221',
      ticketNo: 'C-401',
      price: 40,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '2',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '011522221',
      ticketNo: 'C-200',
      price: 60,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '3',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '012222221',
      ticketNo: 'C-100',
      price: 70,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '4',
      name: ' محمد مجسن',
      image: 'https://example.com/laptop.jpg',
      number: '0115522221',
      ticketNo: 'C-500',
      price: 40,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '5',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '6',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '7',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '0115522221',
      ticketNo: 'C-401',
      price: 40,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '2',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '011522221',
      ticketNo: 'C-200',
      price: 60,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '3',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '012222221',
      ticketNo: 'C-100',
      price: 70,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '8',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '9',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'انور محمود',
      image: 'https://example.com/laptop.jpg',
      number: '01555522221',
      ticketNo: 'C-102',
      price: 20,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '0115522221',
      ticketNo: 'C-300',
      price: 40,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '0115522221',
      ticketNo: 'C-102',
      price: 40,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '0115522221',
      ticketNo: 'C-102',
      price: 40,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
    {
      code: '1',
      name: 'أحمد محمود',
      image: 'https://example.com/laptop.jpg',
      number: '0115522221',
      ticketNo: 'C-102',
      price: 40,
      category: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
      noOfPepole: '2',
      NoPurchases: '2',
      tickt: '2',
    },
  ];
}
